// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PackageTracker.Server.Database;

#nullable disable

namespace PackageTracker.Server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260115095518_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModelsLibrary.Models.PackageInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("PackageInformations");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        },
                        new
                        {
                            Id = 5
                        },
                        new
                        {
                            Id = 6
                        },
                        new
                        {
                            Id = 7
                        },
                        new
                        {
                            Id = 8
                        },
                        new
                        {
                            Id = 9
                        },
                        new
                        {
                            Id = 10
                        });
                });

            modelBuilder.Entity("ModelsLibrary.Models.SenderAndRecipientDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PackageRef")
                        .HasColumnType("int");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PackageRef")
                        .IsUnique();

                    b.ToTable("SenderAndRecipientDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PackageRef = 1,
                            RecipientAddress = "Otherst010",
                            RecipientFirstName = "Some",
                            RecipientLastName = "Guy",
                            RecipientPhone = "123456789",
                            SenderAddress = "Somest101",
                            SenderFirstName = "John",
                            SenderLastName = "Doe",
                            SenderPhone = "888888888"
                        },
                        new
                        {
                            Id = 2,
                            PackageRef = 2,
                            RecipientAddress = "Otherst010",
                            RecipientFirstName = "Some",
                            RecipientLastName = "Guy",
                            RecipientPhone = "123456789",
                            SenderAddress = "Somest101",
                            SenderFirstName = "John",
                            SenderLastName = "Doe",
                            SenderPhone = "888888888"
                        },
                        new
                        {
                            Id = 3,
                            PackageRef = 3,
                            RecipientAddress = "Otherst010",
                            RecipientFirstName = "Some",
                            RecipientLastName = "Guy",
                            RecipientPhone = "123456789",
                            SenderAddress = "Somest101",
                            SenderFirstName = "John",
                            SenderLastName = "Doe",
                            SenderPhone = "888888888"
                        },
                        new
                        {
                            Id = 4,
                            PackageRef = 4,
                            RecipientAddress = "Otherst010",
                            RecipientFirstName = "Some",
                            RecipientLastName = "Guy",
                            RecipientPhone = "123456789",
                            SenderAddress = "Somest101",
                            SenderFirstName = "John",
                            SenderLastName = "Doe",
                            SenderPhone = "888888888"
                        },
                        new
                        {
                            Id = 5,
                            PackageRef = 5,
                            RecipientAddress = "Otherst010",
                            RecipientFirstName = "Some",
                            RecipientLastName = "Guy",
                            RecipientPhone = "123456789",
                            SenderAddress = "Somest101",
                            SenderFirstName = "John",
                            SenderLastName = "Doe",
                            SenderPhone = "888888888"
                        },
                        new
                        {
                            Id = 6,
                            PackageRef = 6,
                            RecipientAddress = "Otherst010",
                            RecipientFirstName = "Some",
                            RecipientLastName = "Guy",
                            RecipientPhone = "123456789",
                            SenderAddress = "Somest101",
                            SenderFirstName = "John",
                            SenderLastName = "Doe",
                            SenderPhone = "888888888"
                        },
                        new
                        {
                            Id = 7,
                            PackageRef = 7,
                            RecipientAddress = "Otherst010",
                            RecipientFirstName = "Some",
                            RecipientLastName = "Guy",
                            RecipientPhone = "123456789",
                            SenderAddress = "Somest101",
                            SenderFirstName = "John",
                            SenderLastName = "Doe",
                            SenderPhone = "888888888"
                        },
                        new
                        {
                            Id = 8,
                            PackageRef = 8,
                            RecipientAddress = "Otherst010",
                            RecipientFirstName = "Some",
                            RecipientLastName = "Guy",
                            RecipientPhone = "123456789",
                            SenderAddress = "Somest101",
                            SenderFirstName = "John",
                            SenderLastName = "Doe",
                            SenderPhone = "888888888"
                        },
                        new
                        {
                            Id = 9,
                            PackageRef = 9,
                            RecipientAddress = "Otherst010",
                            RecipientFirstName = "Some",
                            RecipientLastName = "Guy",
                            RecipientPhone = "123456789",
                            SenderAddress = "Somest101",
                            SenderFirstName = "John",
                            SenderLastName = "Doe",
                            SenderPhone = "888888888"
                        },
                        new
                        {
                            Id = 10,
                            PackageRef = 10,
                            RecipientAddress = "Otherst010",
                            RecipientFirstName = "Some",
                            RecipientLastName = "Guy",
                            RecipientPhone = "123456789",
                            SenderAddress = "Somest101",
                            SenderFirstName = "John",
                            SenderLastName = "Doe",
                            SenderPhone = "888888888"
                        });
                });

            modelBuilder.Entity("ModelsLibrary.Models.StatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DisplayDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PackageRef")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageRef");

                    b.ToTable("StatusHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PackageRef = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            DisplayDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PackageRef = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            DisplayDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PackageRef = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            DisplayDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PackageRef = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            DisplayDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PackageRef = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            DisplayDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PackageRef = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            DisplayDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PackageRef = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            DisplayDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PackageRef = 8,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            DisplayDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PackageRef = 9,
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            DisplayDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PackageRef = 10,
                            Status = 0
                        });
                });

            modelBuilder.Entity("ModelsLibrary.Models.SenderAndRecipientDetails", b =>
                {
                    b.HasOne("ModelsLibrary.Models.PackageInformation", "Package")
                        .WithOne("SenderAndRecipientDetails")
                        .HasForeignKey("ModelsLibrary.Models.SenderAndRecipientDetails", "PackageRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("ModelsLibrary.Models.StatusHistory", b =>
                {
                    b.HasOne("ModelsLibrary.Models.PackageInformation", "Package")
                        .WithMany("TimeStampHistories")
                        .HasForeignKey("PackageRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("ModelsLibrary.Models.PackageInformation", b =>
                {
                    b.Navigation("SenderAndRecipientDetails")
                        .IsRequired();

                    b.Navigation("TimeStampHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
